In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
from src.data import load_raw_data

rides = load_raw_data(year=2022)
rides

File 2022-01 was already in local storage
File 2022-02 was already in local storage
File 2022-03 was already in local storage
File 2022-04 was already in local storage
File 2022-05 was already in local storage
File 2022-06 was already in local storage
File 2022-07 was already in local storage
File 2022-08 was already in local storage
File 2022-09 was already in local storage
File 2022-10 was already in local storage
File 2022-11 was already in local storage
File 2022-12 was already in local storage

            pickup_datetime  pickup_location_id
0       2022-01-01 00:35:40                 142
1       2022-01-01 00:33:43                 236
2       2022-01-01 00:53:21                 166
3       2022-01-01 00:25:21                 114
4       2022-01-01 00:36:48                  68
...                     ...                 ...
3399544 2022-12-31 23:46:00                  16
3399545 2022-12-31 23:13:24                  75
3399546 2022-12-31 23:00:49                 168
3399547 2022-12-31 23:02:50                 238
3399548 2022-12-31 23:00:15                  85

[39654634 rows x 2 columns]

In [2]:
from src.data import transform_raw_data_into_ts_data

ts_data = transform_raw_data_into_ts_data(rides)
ts_data

100%|██████████| 265/265 [00:01<00:00, 177.34it/s]

                pickup_hour  rides  pickup_location_id
0       2022-01-01 00:00:00      0                   1
1       2022-01-01 01:00:00      0                   1
2       2022-01-01 02:00:00      0                   1
3       2022-01-01 03:00:00      0                   1
4       2022-01-01 04:00:00      1                   1
...                     ...    ...                 ...
2321395 2022-12-31 19:00:00      2                 265
2321396 2022-12-31 20:00:00      2                 265
2321397 2022-12-31 21:00:00      7                 265
2321398 2022-12-31 22:00:00      3                 265
2321399 2022-12-31 23:00:00      2                 265

[2321400 rows x 3 columns]

In [21]:
from src.data import transform_ts_data_into_features_and_target

features, targets = transform_ts_data_into_features_and_target(
    ts_data,
    input_seq_len=24*28*1, # one month in hours
    step_size=1, # 1 hour in advance
)

print(f'{features.shape=}')
print(f'{targets.shape=}')

100%|██████████| 265/265 [08:54<00:00,  2.02s/it]

features.shape=(2143055, 674)
targets.shape=(2143055,)

In [22]:
features

,rides_previous_672_hour,rides_previous_671_hour,rides_previous_670_hour,rides_previous_669_hour,rides_previous_668_hour,rides_previous_667_hour,rides_previous_666_hour,rides_previous_665_hour,rides_previous_664_hour,rides_previous_663_hour,...,rides_previous_8_hour,rides_previous_7_hour,rides_previous_6_hour,rides_previous_5_hour,rides_previous_4_hour,rides_previous_3_hour,rides_previous_2_hour,rides_previous_1_hour,pickup_hour,pickup_location_id
0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,...,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,2022-01-29 00:00:00,1
1,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 01:00:00,1
2,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 02:00:00,1
3,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 03:00:00,1
4,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 04:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2143050,9.0,3.0,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,...,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,2022-12-31 18:00:00,265
2143051,3.0,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,...,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2022-12-31 19:00:00,265
2143052,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,...,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2022-12-31 20:00:00,265
2143053,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,4.0,...,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,2022-12-31 21:00:00,265
2143054,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,4.0,8.0,...,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0,2022-12-31 22:00:00,265

In [23]:
targets

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
          ...
2143050    3.0
2143051    2.0
2143052    2.0
2143053    7.0
2143054    3.0
Name: target_rides_next_hour, Length: 2143055, dtype: float32

In [24]:
tabular_data = features
tabular_data['target_rides_next_hour'] = targets

from src.paths import TRANSFORMED_DATA_DIR
tabular_data.to_parquet(TRANSFORMED_DATA_DIR / 'tabular_data.parquet')

In [25]:
tabular_data

,rides_previous_672_hour,rides_previous_671_hour,rides_previous_670_hour,rides_previous_669_hour,rides_previous_668_hour,rides_previous_667_hour,rides_previous_666_hour,rides_previous_665_hour,rides_previous_664_hour,rides_previous_663_hour,...,rides_previous_7_hour,rides_previous_6_hour,rides_previous_5_hour,rides_previous_4_hour,rides_previous_3_hour,rides_previous_2_hour,rides_previous_1_hour,pickup_hour,pickup_location_id,target_rides_next_hour
0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,2022-01-29 00:00:00,1,0.0
1,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 01:00:00,1,0.0
2,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 02:00:00,1,0.0
3,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 03:00:00,1,0.0
4,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-29 04:00:00,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2143050,9.0,3.0,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,...,5.0,2.0,2.0,4.0,4.0,2.0,4.0,2022-12-31 18:00:00,265,3.0
2143051,3.0,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,...,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2022-12-31 19:00:00,265,2.0
2143052,4.0,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,...,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2022-12-31 20:00:00,265,2.0
2143053,4.0,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,4.0,...,4.0,4.0,2.0,4.0,3.0,2.0,2.0,2022-12-31 21:00:00,265,7.0
2143054,2.0,9.0,4.0,7.0,1.0,4.0,8.0,5.0,4.0,8.0,...,4.0,2.0,4.0,3.0,2.0,2.0,7.0,2022-12-31 22:00:00,265,3.0

In [28]:
tabular_data.pickup_hour.dt.hour.value_counts().sort_index()

pickup_hour
0     89305
1     89305
2     89305
3     89305
4     89305
5     89305
6     89305
7     89305
8     89305
9     89305
10    89305
11    89305
12    89305
13    89305
14    89305
15    89305
16    89305
17    89305
18    89305
19    89305
20    89305
21    89305
22    89305
23    89040
Name: count, dtype: int64